### ISSUE TITLE
Invalid byte sequence in US-ASCII exception when locales are not set as expected

### ISSUE THREAD

**Issue by danieloliveira079** [Shopify/krane#395]
# Bug report

When using `kubernetes-deploy`, if the locales is not set accordingly it may thrown an exception in cases where the log output from a pod contains non US-ASCII characters.

The environment where the process has been executed was a `ruby:2.3.3` container without any special packages or configs. It was pretty much `docker run -it --rm --name deployer bash`.

From the `bash` session `kubernetes-deploy ...`

**Expected behavior:**

The output of the `provision` container which contains pure text lines as well as some json formatted messages to show up on the `kubernetes-deploy` logs.

**Actual behavior:** 

The following message is thrown and the deployment process breaks.

```
[INFO][2018-12-05 16:07:04 +0000]	Deploying Pod/provision-e03421f6-e9aae851 (timeout: 600s)
/usr/local/lib/ruby/2.3.0/shellwords.rb:142:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/lib/ruby/2.3.0/shellwords.rb:142:in `shellescape'
	from /usr/local/lib/ruby/2.3.0/shellwords.rb:208:in `shellescape'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/kubectl.rb:28:in `run'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/kubernetes_resource/pod.rb:98:in `block in fetch_logs'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/kubernetes_resource/pod.rb:90:in `each'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/kubernetes_resource/pod.rb:90:in `each_with_object'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/kubernetes_resource/pod.rb:90:in `fetch_logs'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/kubernetes_resource/pod.rb:143:in `display_logs'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/kubernetes_resource/pod.rb:36:in `sync'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/sync_mediator.rb:44:in `block in sync'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/concurrency.rb:13:in `each'
	from /usr/local/bundle/gems/kubernetes-deploy-0.20.5/lib/kubernetes-deploy/concurrency.rb:13:in `block (2 levels) in split_across_threads'
```

**Version(s) affected:** 
0.22.0

### Steps to Reproduce

1. Execute `kubernetes-deploy --template-dir="${TEMPLATE_DIR}" --bindings=current_sha="${REVISION}",prev_sha="${prev_commit:-$REVISION}",environment="${ENVIRONMENT}" "${NAMESPACE}" "${CONTEXT}"`
2. Wait for pod output. It is important the your pod should output a message similar to:
```
{"message":"Any message.","context":[],"level":200,"level_name":"INFO","channel":"k8s","datetime":{"date":"2018-12-05 16:12:36.239316","timezone_type":3,"timezone":"UTC"},"extra":[],"timestamp":"2018-12-05T16:12:36.239Z"}
```

**Workaround**

The following commands worked for setting up the right locales and suppress the exception:

```
apt-get update && apt-get install locales
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en  
export LC_ALL=en_US.UTF-8 
```
and then
```
kubernetes-deploy ...
```

**Comment by KnVerey** [comment]
Thanks for the report. Looks like it is `out.shellescape`, which is being done for the purposes of generating a debug line that is only printed if `DEBUG=1`. That line is changed on master, but we're still doing a `gsub` so I bet it will still 💥 . We should fix this and add a test, but also potentially stop generating doing the gsub unless `logger.debug?`.

**Comment by dturn** [comment]
We've removed the use of `shellescape` so this should no longer occur. If it is please re-open with an updated stack trace.

**Comment by j0npulsifer** [comment]
I ran into this problem today, looks like the same gsub. Fixed by generating the locales and exporting `LANG=en_US.UTF-8` at run time as mentioned.

```raw
[INFO][2019-11-10 23:30:19 +0000][gke_kubesec_us-east4-b_lab][wishlist]
[INFO][2019-11-10 23:30:19 +0000][gke_kubesec_us-east4-b_lab][wishlist] ------------------------------------Phase 1: Initializing deploy------------------------------------                                                                                                                                
[INFO][2019-11-10 23:30:21 +0000][gke_kubesec_us-east4-b_lab][wishlist] All required parameters and files are present
[INFO][2019-11-10 23:30:21 +0000][gke_kubesec_us-east4-b_lab][wishlist] Discovering resources:
/usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/kubectl.rb:37:in `gsub': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/kubectl.rb:37:in `block in run'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/kubectl.rb:34:in `each'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/kubectl.rb:34:in `run'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/cluster_resource_discovery.rb:45:in `fetch_crds'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/cluster_resource_discovery.rb:13:in `crds'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/deploy_task.rb:337:in `discover_resources'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/statsd.rb:55:in `block in measure_method'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/deploy_task.rb:170:in `run!'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/krane/cli/deploy_command.rb:68:in `block in from_options'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/kubernetes-deploy/options_helper.rb:28:in `with_processed_template_paths'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/krane/cli/deploy_command.rb:54:in `from_options'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/krane/cli/krane.rb:57:in `block in deploy'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/krane/cli/krane.rb:68:in `rescue_and_exit'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/lib/krane/cli/krane.rb:56:in `deploy'
        from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /usr/local/bundle/gems/kubernetes-deploy-0.30.0/exe/krane:5:in `<top (required)>'
        from /usr/local/bundle/bin/krane:23:in `load'
        from /usr/local/bundle/bin/krane:23:in `<main>'
```
