### ISSUE TITLE
2.1.6+ error deploying 

### ISSUE THREAD

**Issue by strowi** [Shopify/krane#808]
# Bug report

[Description of the bug]

**Expected behavior:** successful deployment with v2.1.6+

**Actual behavior:** Deployment fails with:
```# testing k8s-connection:
Kubernetes master is running at https://rancher02.XYZ.net/k8s/clusters/c-testing
CoreDNS is running at https://rancher02.XYZ.net/k8s/clusters/c-testing/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
KubeDNSUpstream is running at https://rancher02.XYZ.net/k8s/clusters/c-testing/api/v1/namespaces/kube-system/services/kube-dns-upstream:dns/proxy
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
  - no global resources to deploy. 
# checking/creating namespace haproxy-exporter
NAME                              STATUS   AGE
haproxy-exporter   Active   461d
secret "ejson-keys" deleted
secret/ejson-keys created
# deploying to haproxy-exporter... 
[INFO][2021-02-23 14:32:22 +0000] 
[INFO][2021-02-23 14:32:22 +0000] ---------------------------------Phase 1: Initializing render task----------------------------------
[INFO][2021-02-23 14:32:22 +0000] Validating configuration
[INFO][2021-02-23 14:32:22 +0000] 
[INFO][2021-02-23 14:32:22 +0000] -----------------------------------Phase 2: Rendering template(s)-----------------------------------
[INFO][2021-02-23 14:32:22 +0000] Rendering 00_imagePullSecret_hub_xyz_net.yml...
[INFO][2021-02-23 14:32:22 +0000] Rendered 00_imagePullSecret_hub_xyz_net.yml
[INFO][2021-02-23 14:32:22 +0000] Rendering haproxy-exporter-deployment.yml.erb...
[INFO][2021-02-23 14:32:22 +0000] Rendered haproxy-exporter-deployment.yml.erb
[INFO][2021-02-23 14:32:22 +0000] 
[INFO][2021-02-23 14:32:22 +0000] ------------------------------------------Result: SUCCESS-------------------------------------------
[INFO][2021-02-23 14:32:22 +0000] Successfully rendered 2 template(s)
[INFO][2021-02-23 14:32:22 +0000] 
[INFO][2021-02-23 14:32:25 +0000] 
[INFO][2021-02-23 14:32:25 +0000] ------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2021-02-23 14:32:27 +0000] All required parameters and files are present
[INFO][2021-02-23 14:32:27 +0000] Discovering resources:
/usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/cluster_resource_discovery.rb:63:in `api_paths': private method `select' called for nil:NilClass (NoMethodError)
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/cluster_resource_discovery.rb:32:in `fetch_resources'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/task_config.rb:19:in `global_kinds'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/deploy_task.rb:243:in `block in discover_resources'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:140:in `block in with_resource_definitions'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:133:in `block (2 levels) in with_resource_definitions_and_filename'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:31:in `block (2 levels) in with_resource_definitions_and_filename'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:86:in `block in templates'
  from /usr/lib/ruby/2.7.0/psych.rb:562:in `block in load_stream'
  from /usr/lib/ruby/2.7.0/psych/handlers/document_stream.rb:19:in `end_document'
  from /usr/lib/ruby/2.7.0/psych.rb:456:in `parse'
  from /usr/lib/ruby/2.7.0/psych.rb:456:in `parse_stream'
  from /usr/lib/ruby/2.7.0/psych.rb:561:in `load_stream'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:80:in `templates'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:31:in `block in with_resource_definitions_and_filename'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/delayed_exceptions.rb:8:in `block in with_delayed_exceptions'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/delayed_exceptions.rb:6:in `each'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/delayed_exceptions.rb:6:in `with_delayed_exceptions'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:29:in `with_resource_definitions_and_filename'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:128:in `block in with_resource_definitions_and_filename'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/delayed_exceptions.rb:8:in `block in with_delayed_exceptions'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/delayed_exceptions.rb:6:in `each'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/delayed_exceptions.rb:6:in `with_delayed_exceptions'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:127:in `with_resource_definitions_and_filename'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/template_sets.rb:139:in `with_resource_definitions'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/deploy_task.rb:240:in `discover_resources'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/statsd.rb:41:in `block in measure_method'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/deploy_task.rb:147:in `run!'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/cli/deploy_command.rb:66:in `block in from_options'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/options_helper.rb:24:in `with_processed_template_paths'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/cli/deploy_command.rb:55:in `from_options'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/cli/krane.rb:58:in `block in deploy'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/cli/krane.rb:77:in `rescue_and_exit'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/lib/krane/cli/krane.rb:57:in `deploy'
  from /usr/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  from /usr/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  from /usr/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  from /usr/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  from /usr/lib/ruby/gems/2.7.0/gems/krane-2.1.6/exe/krane:5:in `<top (required)>'
  from /usr/bin/krane:23:in `load'
  from /usr/bin/krane:23:in `<main>'
```

**Version(s) affected:** [run `krane version`]
v2.1.6/v2.1.7

### Steps to Reproduce

1. render + deploy with krane-v.2.1.5 to k8s-1.18.14 -> works
2. render + deploy with krane-v.2.1.6+ to k8s-1.18.14  -> error

Not sure what else might be useful info.. happy to provide more details if needed.;)

regards,
strowi

**Comment by dturn** [comment]
@strowi Thanks for filing a bug report. This is definately unexpected. To help us debug can you run `kubecetl get --raw /` and send us back the results? (There shouldn't be anything sensitive in the results, but you should double check before posting to  public issue).

**Comment by strowi** [comment]
@dturn as requested:
```json
{
  "type": "collection",
  "links": {
    "self": "https://rancher02.XYZ.net/"
  },
  "actions": {},
  "pagination": {
    "limit": 1000,
    "total": 4
  },
  "sort": {
    "order": "asc",
    "reverse": "https://rancher02.XYZ.net/?order=desc"
  },
  "resourceType": "apiRoot",
  "data": [
    {
      "apiVersion": {
        "group": "meta.cattle.io",
        "path": "/meta",
        "version": "v1"
      },
      "baseType": "apiRoot",
      "links": {
        "apiRoots": "https://rancher02.XYZ.net/meta/apiroots",
        "root": "https://rancher02.XYZ.net/meta",
        "schemas": "https://rancher02.XYZ.net/meta/schemas",
        "self": "https://rancher02.XYZ.net/meta",
        "subscribe": "https://rancher02.XYZ.net/meta/subscribe"
      },
      "type": "apiRoot"
    },
    {
      "apiVersion": {
        "group": "management.cattle.io",
        "path": "/v3",
        "version": "v3"
      },
      "baseType": "apiRoot",
      "links": {
        "authConfigs": "https://rancher02.XYZ.net/v3/authconfigs",
        "catalogs": "https://rancher02.XYZ.net/v3/catalogs",
        "cisBenchmarkVersions": "https://rancher02.XYZ.net/v3/cisbenchmarkversions",
        "cisConfigs": "https://rancher02.XYZ.net/v3/cisconfigs",
        "cloudCredentials": "https://rancher02.XYZ.net/v3/cloudcredentials",
        "clusterAlertGroups": "https://rancher02.XYZ.net/v3/clusteralertgroups",
        "clusterAlertRules": "https://rancher02.XYZ.net/v3/clusteralertrules",
        "clusterAlerts": "https://rancher02.XYZ.net/v3/clusteralerts",
        "clusterCatalogs": "https://rancher02.XYZ.net/v3/clustercatalogs",
        "clusterLoggings": "https://rancher02.XYZ.net/v3/clusterloggings",
        "clusterMonitorGraphs": "https://rancher02.XYZ.net/v3/clustermonitorgraphs",
        "clusterRegistrationTokens": "https://rancher02.XYZ.net/v3/clusterregistrationtokens",
        "clusterRoleTemplateBindings": "https://rancher02.XYZ.net/v3/clusterroletemplatebindings",
        "clusterScans": "https://rancher02.XYZ.net/v3/clusterscans",
        "clusterTemplateRevisions": "https://rancher02.XYZ.net/v3/clustertemplaterevisions",
        "clusterTemplates": "https://rancher02.XYZ.net/v3/clustertemplates",
        "clusters": "https://rancher02.XYZ.net/v3/clusters",
        "composeConfigs": "https://rancher02.XYZ.net/v3/composeconfigs",
        "dynamicSchemas": "https://rancher02.XYZ.net/v3/dynamicschemas",
        "etcdBackups": "https://rancher02.XYZ.net/v3/etcdbackups",
        "features": "https://rancher02.XYZ.net/v3/features",
        "fleetWorkspaces": "https://rancher02.XYZ.net/v3/fleetworkspaces",
        "globalDnsProviders": "https://rancher02.XYZ.net/v3/globaldnsproviders",
        "globalDnses": "https://rancher02.XYZ.net/v3/globaldnses",
        "globalRoleBindings": "https://rancher02.XYZ.net/v3/globalrolebindings",
        "globalRoles": "https://rancher02.XYZ.net/v3/globalroles",
        "groupMembers": "https://rancher02.XYZ.net/v3/groupmembers",
        "groups": "https://rancher02.XYZ.net/v3/groups",
        "kontainerDrivers": "https://rancher02.XYZ.net/v3/kontainerdrivers",
        "ldapConfigs": "https://rancher02.XYZ.net/v3/ldapconfigs",
        "managementSecrets": "https://rancher02.XYZ.net/v3/managementsecrets",
        "monitorMetrics": "https://rancher02.XYZ.net/v3/monitormetrics",
        "multiClusterAppRevisions": "https://rancher02.XYZ.net/v3/multiclusterapprevisions",
        "multiClusterApps": "https://rancher02.XYZ.net/v3/multiclusterapps",
        "nodeDrivers": "https://rancher02.XYZ.net/v3/nodedrivers",
        "nodePools": "https://rancher02.XYZ.net/v3/nodepools",
        "nodeTemplates": "https://rancher02.XYZ.net/v3/nodetemplates",
        "nodes": "https://rancher02.XYZ.net/v3/nodes",
        "notifiers": "https://rancher02.XYZ.net/v3/notifiers",
        "podSecurityPolicyTemplateProjectBindings": "https://rancher02.XYZ.net/v3/podsecuritypolicytemplateprojectbindings",
        "podSecurityPolicyTemplates": "https://rancher02.XYZ.net/v3/podsecuritypolicytemplates",
        "preferences": "https://rancher02.XYZ.net/v3/preferences",
        "principals": "https://rancher02.XYZ.net/v3/principals",
        "projectAlertGroups": "https://rancher02.XYZ.net/v3/projectalertgroups",
        "projectAlertRules": "https://rancher02.XYZ.net/v3/projectalertrules",
        "projectAlerts": "https://rancher02.XYZ.net/v3/projectalerts",
        "projectCatalogs": "https://rancher02.XYZ.net/v3/projectcatalogs",
        "projectLoggings": "https://rancher02.XYZ.net/v3/projectloggings",
        "projectMonitorGraphs": "https://rancher02.XYZ.net/v3/projectmonitorgraphs",
        "projectNetworkPolicies": "https://rancher02.XYZ.net/v3/projectnetworkpolicies",
        "projectRoleTemplateBindings": "https://rancher02.XYZ.net/v3/projectroletemplatebindings",
        "projects": "https://rancher02.XYZ.net/v3/projects",
        "rkeAddons": "https://rancher02.XYZ.net/v3/rkeaddons",
        "rkeK8sServiceOptions": "https://rancher02.XYZ.net/v3/rkek8sserviceoptions",
        "rkeK8sSystemImages": "https://rancher02.XYZ.net/v3/rkek8ssystemimages",
        "roleTemplates": "https://rancher02.XYZ.net/v3/roletemplates",
        "root": "https://rancher02.XYZ.net/v3",
        "samlTokens": "https://rancher02.XYZ.net/v3/samltokens",
        "self": "https://rancher02.XYZ.net/v3",
        "settings": "https://rancher02.XYZ.net/v3/settings",
        "subscribe": "https://rancher02.XYZ.net/v3/subscribe",
        "templateVersions": "https://rancher02.XYZ.net/v3/templateversions",
        "templates": "https://rancher02.XYZ.net/v3/templates",
        "tokens": "https://rancher02.XYZ.net/v3/tokens",
        "users": "https://rancher02.XYZ.net/v3/users"
      },
      "type": "apiRoot"
    },
    {
      "apiVersion": {
        "group": "cluster.cattle.io",
        "path": "/v3/cluster",
        "version": "v3"
      },
      "baseType": "apiRoot",
      "links": {
        "apiServices": "https://rancher02.XYZ.net/v3/cluster/apiservices",
        "namespaces": "https://rancher02.XYZ.net/v3/cluster/namespaces",
        "persistentVolumes": "https://rancher02.XYZ.net/v3/cluster/persistentvolumes",
        "root": "https://rancher02.XYZ.net/v3/cluster",
        "self": "https://rancher02.XYZ.net/v3/cluster",
        "storageClasses": "https://rancher02.XYZ.net/v3/cluster/storageclasses",
        "subscribe": "https://rancher02.XYZ.net/v3/cluster/subscribe"
      },
      "type": "apiRoot"
    },
    {
      "apiVersion": {
        "group": "project.cattle.io",
        "path": "/v3/project",
        "version": "v3"
      },
      "baseType": "apiRoot",
      "links": {
        "alertmanagers": "https://rancher02.XYZ.net/v3/project/alertmanagers",
        "appRevisions": "https://rancher02.XYZ.net/v3/project/apprevisions",
        "apps": "https://rancher02.XYZ.net/v3/project/apps",
        "basicAuths": "https://rancher02.XYZ.net/v3/project/basicauths",
        "certificates": "https://rancher02.XYZ.net/v3/project/certificates",
        "configMaps": "https://rancher02.XYZ.net/v3/project/configmaps",
        "cronJobs": "https://rancher02.XYZ.net/v3/project/cronjobs",
        "daemonSets": "https://rancher02.XYZ.net/v3/project/daemonsets",
        "deployments": "https://rancher02.XYZ.net/v3/project/deployments",
        "destinationRules": "https://rancher02.XYZ.net/v3/project/destinationrules",
        "dnsRecords": "https://rancher02.XYZ.net/v3/project/dnsrecords",
        "dockerCredentials": "https://rancher02.XYZ.net/v3/project/dockercredentials",
        "gateways": "https://rancher02.XYZ.net/v3/project/gateways",
        "horizontalPodAutoscalers": "https://rancher02.XYZ.net/v3/project/horizontalpodautoscalers",
        "ingresses": "https://rancher02.XYZ.net/v3/project/ingresses",
        "jobs": "https://rancher02.XYZ.net/v3/project/jobs",
        "namespacedBasicAuths": "https://rancher02.XYZ.net/v3/project/namespacedbasicauths",
        "namespacedCertificates": "https://rancher02.XYZ.net/v3/project/namespacedcertificates",
        "namespacedDockerCredentials": "https://rancher02.XYZ.net/v3/project/namespaceddockercredentials",
        "namespacedSecrets": "https://rancher02.XYZ.net/v3/project/namespacedsecrets",
        "namespacedServiceAccountTokens": "https://rancher02.XYZ.net/v3/project/namespacedserviceaccounttokens",
        "namespacedSshAuths": "https://rancher02.XYZ.net/v3/project/namespacedsshauths",
        "persistentVolumeClaims": "https://rancher02.XYZ.net/v3/project/persistentvolumeclaims",
        "pipelineExecutions": "https://rancher02.XYZ.net/v3/project/pipelineexecutions",
        "pipelineSettings": "https://rancher02.XYZ.net/v3/project/pipelinesettings",
        "pipelines": "https://rancher02.XYZ.net/v3/project/pipelines",
        "pods": "https://rancher02.XYZ.net/v3/project/pods",
        "prometheusRules": "https://rancher02.XYZ.net/v3/project/prometheusrules",
        "prometheuses": "https://rancher02.XYZ.net/v3/project/prometheuses",
        "replicaSets": "https://rancher02.XYZ.net/v3/project/replicasets",
        "replicationControllers": "https://rancher02.XYZ.net/v3/project/replicationcontrollers",
        "root": "https://rancher02.XYZ.net/v3/project",
        "secrets": "https://rancher02.XYZ.net/v3/project/secrets",
        "self": "https://rancher02.XYZ.net/v3/project",
        "serviceAccountTokens": "https://rancher02.XYZ.net/v3/project/serviceaccounttokens",
        "serviceMonitors": "https://rancher02.XYZ.net/v3/project/servicemonitors",
        "services": "https://rancher02.XYZ.net/v3/project/services",
        "sourceCodeCredentials": "https://rancher02.XYZ.net/v3/project/sourcecodecredentials",
        "sourceCodeProviderConfigs": "https://rancher02.XYZ.net/v3/project/sourcecodeproviderconfigs",
        "sourceCodeProviders": "https://rancher02.XYZ.net/v3/project/sourcecodeproviders",
        "sourceCodeRepositories": "https://rancher02.XYZ.net/v3/project/sourcecoderepositories",
        "sshAuths": "https://rancher02.XYZ.net/v3/project/sshauths",
        "statefulSets": "https://rancher02.XYZ.net/v3/project/statefulsets",
        "subscribe": "https://rancher02.XYZ.net/v3/project/subscribe",
        "virtualServices": "https://rancher02.XYZ.net/v3/project/virtualservices",
        "workloads": "https://rancher02.XYZ.net/v3/project/workloads"
      },
      "type": "apiRoot"
    }
  ]
}
```

**Comment by dturn** [comment]
Hmmm, that's unexpected. Against minikube / our gke clusters we get a response that looks like:

```
{
  "paths": [
    "/api",
    "/api/v1",
    ...
    ]
}
```

I wonder if this is on a different path with clusters created by rancher, a quick google search didn't turn anything up.

**Comment by strowi** [comment]
Ahh, yep they are. It seems to be located underneath `kubectl get --raw /k8s/clusters/c-mzbmh` where 'c-mzbmh' is the cluster-id. 
Found a reference here at the very end: https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/horitzontal-pod-autoscaler/manage-hpa-with-kubectl/

```
~> kubectl get --raw /k8s/clusters/c-mzbmh
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/acme.cert-manager.io",
    "/apis/acme.cert-manager.io/v1",
    "/apis/acme.cert-manager.io/v1alpha2",
    "/apis/acme.cert-manager.io/v1alpha3",
    "/apis/acme.cert-manager.io/v1beta1",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1",
    "/apis/admissionregistration.k8s.io/v1beta1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apiregistration.k8s.io/v1beta1",
    "/apis/apps",
    "/apis/apps/v1",
    "/apis/authentication.istio.io",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/autoscaling/v2beta1",
    "/apis/autoscaling/v2beta2",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v1beta1",
    "/apis/catalog.cattle.io",
    "/apis/catalog.cattle.io/v1",
    "/apis/cert-manager.io",
    "/apis/cert-manager.io/v1",
    "/apis/cert-manager.io/v1alpha2",
    "/apis/cert-manager.io/v1alpha3",
    "/apis/cert-manager.io/v1beta1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1beta1",
    "/apis/certmanager.k8s.io",
    "/apis/certmanager.k8s.io/v1alpha1",
    "/apis/cis.cattle.io",
    "/apis/cis.cattle.io/v1",
    "/apis/cluster.cattle.io",
    "/apis/cluster.cattle.io/v3",
    "/apis/config.istio.io",
    "/apis/config.istio.io/v1alpha2",
    "/apis/coordination.k8s.io",
    "/apis/coordination.k8s.io/v1",
    "/apis/coordination.k8s.io/v1beta1",
    "/apis/crd.projectcalico.org",
    "/apis/crd.projectcalico.org/v1",
    "/apis/custom.metrics.k8s.io",
    "/apis/custom.metrics.k8s.io/v1beta1",
    "/apis/discovery.k8s.io",
    "/apis/discovery.k8s.io/v1beta1",
    "/apis/events.k8s.io",
    "/apis/events.k8s.io/v1beta1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/install.istio.io",
    "/apis/install.istio.io/v1alpha1",
    "/apis/jaegertracing.io",
    "/apis/jaegertracing.io/v1",
    "/apis/longhorn.io",
    "/apis/longhorn.io/v1beta1",
    "/apis/management.cattle.io",
    "/apis/management.cattle.io/v3",
    "/apis/metrics.k8s.io",
    "/apis/metrics.k8s.io/v1beta1",
    "/apis/monitoring.coreos.com",
    "/apis/monitoring.coreos.com/v1",
    "/apis/monitoring.kiali.io",
    "/apis/monitoring.kiali.io/v1alpha1",
    "/apis/networking.istio.io",
    "/apis/networking.istio.io/v1alpha3",
    "/apis/networking.istio.io/v1beta1",
    "/apis/networking.k8s.io",
    "/apis/networking.k8s.io/v1",
    "/apis/networking.k8s.io/v1beta1",
    "/apis/node.k8s.io",
    "/apis/node.k8s.io/v1beta1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/rbac.istio.io",
    "/apis/scheduling.k8s.io",
    "/apis/scheduling.k8s.io/v1",
    "/apis/scheduling.k8s.io/v1beta1",
    "/apis/security.istio.io",
    "/apis/security.istio.io/v1beta1",
    "/apis/snapshot.storage.k8s.io",
    "/apis/snapshot.storage.k8s.io/v1alpha1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/autoregister-completion",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/apiservice-openapi-controller",
    "/healthz/poststarthook/apiservice-registration-controller",
    "/healthz/poststarthook/apiservice-status-available-controller",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/crd-informer-synced",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/kube-apiserver-autoregistration",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/healthz/poststarthook/scheduling/bootstrap-system-priority-classes",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/healthz/poststarthook/start-cluster-authentication-info-controller",
    "/healthz/poststarthook/start-kube-aggregator-informers",
    "/healthz/poststarthook/start-kube-apiserver-admission-initializer",
    "/livez",
    "/livez/autoregister-completion",
    "/livez/etcd",
    "/livez/log",
    "/livez/ping",
    "/livez/poststarthook/apiservice-openapi-controller",
    "/livez/poststarthook/apiservice-registration-controller",
    "/livez/poststarthook/apiservice-status-available-controller",
    "/livez/poststarthook/bootstrap-controller",
    "/livez/poststarthook/crd-informer-synced",
    "/livez/poststarthook/generic-apiserver-start-informers",
    "/livez/poststarthook/kube-apiserver-autoregistration",
    "/livez/poststarthook/rbac/bootstrap-roles",
    "/livez/poststarthook/scheduling/bootstrap-system-priority-classes",
    "/livez/poststarthook/start-apiextensions-controllers",
    "/livez/poststarthook/start-apiextensions-informers",
    "/livez/poststarthook/start-cluster-authentication-info-controller",
    "/livez/poststarthook/start-kube-aggregator-informers",
    "/livez/poststarthook/start-kube-apiserver-admission-initializer",
    "/logs",
    "/metrics",
    "/openapi/v2",
    "/readyz",
    "/readyz/autoregister-completion",
    "/readyz/etcd",
    "/readyz/informer-sync",
    "/readyz/log",
    "/readyz/ping",
    "/readyz/poststarthook/apiservice-openapi-controller",
    "/readyz/poststarthook/apiservice-registration-controller",
    "/readyz/poststarthook/apiservice-status-available-controller",
    "/readyz/poststarthook/bootstrap-controller",
    "/readyz/poststarthook/crd-informer-synced",
    "/readyz/poststarthook/generic-apiserver-start-informers",
    "/readyz/poststarthook/kube-apiserver-autoregistration",
    "/readyz/poststarthook/rbac/bootstrap-roles",
    "/readyz/poststarthook/scheduling/bootstrap-system-priority-classes",
    "/readyz/poststarthook/start-apiextensions-controllers",
    "/readyz/poststarthook/start-apiextensions-informers",
    "/readyz/poststarthook/start-cluster-authentication-info-controller",
    "/readyz/poststarthook/start-kube-aggregator-informers",
    "/readyz/poststarthook/start-kube-apiserver-admission-initializer",
    "/readyz/shutdown",
    "/version"
  ]
}%        
```

**Comment by strowi** [comment]
Digging around, i found out it's quite easy if you know your kubectl: ;)

```
~> kubectl config view --minify --output jsonpath="{.clusters[*].cluster.server}"
https://rancher02.xyz.net/k8s/clusters/c-testing
```
