### ISSUE TITLE
uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState

### ISSUE THREAD

**Issue by bcha** [Shopify/krane#851]
# Bug report

krane blows up on deploy since last night. Possibly related to Rails 7.0.0 release? See similar: https://github.com/rails/rails/issues/43889

-> Need to require top level active_support in krane too? I'm not too familiar with Ruby myself.

**Expected behavior:** krane doesnt blow up

**Actual behavior:** krane blows up

**Version(s) affected:** Both 2.3.0 & 2.3.4 are affected.

### Steps to Reproduce

Run krane deploy:

```
$ krane deploy ${NAMESPACE} ${KUBE_CONTEXT} -f ./k8s/overlays/${ENVIRONMENT}/kustomized/${ENVIRONMENT}.yml --global-timeout=${KRANE_GLOBAL_TIMEOUT} ${KRANE_EXTRA_ARGS}
/usr/local/bundle/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
	from /usr/local/bundle/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:103:in `backend='
	from /usr/local/bundle/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /usr/local/bundle/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/activesupport-7.0.0/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/activesupport-7.0.0/lib/active_support/duration.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/activesupport-7.0.0/lib/active_support/core_ext/numeric/time.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/krane-2.3.0/lib/krane/common.rb:6:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/krane-2.3.0/lib/krane/deploy_task.rb:8:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/krane-2.3.0/lib/krane.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/krane-2.3.0/lib/krane/cli/krane.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/krane-2.3.0/exe/krane:4:in `<top (required)>'
	from /usr/local/bundle/bin/krane:23:in `load'
	from /usr/local/bundle/bin/krane:23:in `<main>'
```

**Comment by ibratoev** [comment]
The blew up our updates as well. I consider it a critical issue because it breaks clean installs of `krane`.

**Comment by sonalkr132** [comment]
I just want to voice my support for this. It broke our deployments after update of shipit-engine. krane is not usable with activesupport 7.

**Comment by simi** [comment]
Isn't https://github.com/Shopify/krane/pull/861 fixing this?

**Comment by benlangfeld** [comment]
@simi Indeed. Y'all just need to upgrade krane. This issue can be closed.
