### ISSUE TITLE
krane restart hits testing code path and silently fails

### ISSUE THREAD

**Issue by saunderst** [Shopify/krane#893]
# Bug report

When running `krane restart` via https://github.com/Shopify/shopify-core-datastores/blob/master/restart.rb, a low-level function call in the `faraday` dependency failed.  The stack trace showed that test adapter code was invoked (and failed with `Faraday::Adapter::Test::Stubs::NotFound`):
```
[38;5;48m2022-05-26 20:26:10 INFO  [0m [38;5;243mdeploy-agent-5885666478-xw7x4[0m [0m[Process] Process is running with PID: 311[0m
./restart.rb master shopify-datastores core-eu-we3-xq75 --current-sha=5f0fddd4f53518d452c4caec7a1266e11fd8c539 -f 0181020b-37d1-4f8a-9abf-bd9708ca2aa7/core-eu-we3-xq75/shopify-datastores --bindings='"cluster_name=core-eu-we3-xq75","cluster_location=gcp-europe-west3","cluster_project=shopify-cloud-core","cluster_region=europe-west3","cluster_role=apps","cluster_tier=core","cluster_environment=production","cluster_profile=core-full","cluster_jurisdiction=unrestricted"'
SHARDS: master
Deployments: ["proxysql-master"]
Executing: krane restart shopify-datastores core-eu-we3-xq75 --global-timeout=1800s --deployments=proxysql-master
[INFO][2022-05-26 20:26:32 +0000]
[INFO][2022-05-26 20:26:32 +0000]	[0;36;49m-----------------------------------Phase 1: Initializing restart[0m[0;36;49m------------------------------------[0m
[INFO][2022-05-26 20:26:36 +0000]	Configured to restart deployments by name: proxysql-master
/root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/faraday-2.0.0.alpha.pre.4/lib/faraday/adapter/test.rb:245:in `call': no stubbed request for get http://169.254.169.254  (Faraday::Adapter::Test::Stubs::NotFound)
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/faraday-2.0.0.alpha.pre.4/lib/faraday/request/url_encoded.rb:25:in `call'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/faraday-2.0.0.alpha.pre.4/lib/faraday/rack_builder.rb:154:in `build_response'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/faraday-2.0.0.alpha.pre.4/lib/faraday/connection.rb:445:in `run_request'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/faraday-2.0.0.alpha.pre.4/lib/faraday/connection.rb:200:in `get'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/googleauth-0.17.1/lib/googleauth/compute_engine.rb:90:in `on_gce?'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/memoist-0.16.2/lib/memoist.rb:213:in `on_gce?'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/googleauth-0.17.1/lib/googleauth/application_default.rb:73:in `get_application_default'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/kubeclient-4.9.3/lib/kubeclient/google_application_default_credentials.rb:25:in `token'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/kubeclient-4.9.3/lib/kubeclient/gcp_auth_provider.rb:14:in `token'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/kubeclient-4.9.3/lib/kubeclient/config.rb:189:in `fetch_token_from_provider'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/kubeclient-4.9.3/lib/kubeclient/config.rb:176:in `fetch_user_auth_options'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/kubeclient-4.9.3/lib/kubeclient/config.rb:56:in `context'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/kubeclient_builder.rb:143:in `build_kubeclient'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/kubeclient_builder.rb:61:in `build_apps_v1_kubeclient'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/restart_task.rb:330:in `apps_v1_kubeclient'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/restart_task.rb:263:in `block in fetch_deployments'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/restart_task.rb:260:in `map'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/restart_task.rb:260:in `fetch_deployments'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/restart_task.rb:159:in `identify_target_workloads_by_name'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/restart_task.rb:131:in `identify_target_workloads'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/restart_task.rb:69:in `run!'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/cli/restart_command.rb:30:in `from_options'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/cli/krane.rb:42:in `block in restart'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/cli/krane.rb:77:in `rescue_and_exit'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/lib/krane/cli/krane.rb:41:in `restart'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
from /root/local/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/krane-2.4.6/exe/krane:5:in `<top (required)>'
from /root/local/ruby-3.1.2/bin/krane:25:in `load'
from /root/local/ruby-3.1.2/bin/krane:25:in `<main>'
[38;5;48m2022-05-26 20:26:40 INFO  [0m [38;5;243mdeploy-agent-5885666478-xw7x4[0m [0mProcess with PID: 311 finished with Exit Status: 0[0m
```

Also, gem version `faraday-2.0.0.alpha.pre.4` seems suspect.

**Expected behavior:**

`restart` task would cause the target service to restart, or an error would be signalled.

**Actual behavior:**

Task silently failed (aside from logging stack trace) and returned `0` exit status.

**Version(s) affected:**

2.4.6

### Steps to Reproduce

Run ProxySQL restart task here: https://shipit.shopify.io/shopify/shopify-core-datastores/production/tasks/restart-all/new

**Comment by jpfourny** [comment]
`krane` only distributes a gemspec, not a lockfile, so dependency versions are controlled by you - `krane` does not directly constrain `faraday`. 

Regardless, I see that the `rack` adapter is active in the stack trace you gave - is that expected? Rack always uses a mock / test session. 

```ruby
class Rack < Faraday::Adapter
      dependency 'rack/test'

      # not prefixed with "HTTP_"
      SPECIAL_HEADERS = %w[CONTENT_LENGTH CONTENT_TYPE].freeze

      def initialize(faraday_app, rack_app)
        super(faraday_app)
        mock_session = ::Rack::MockSession.new(rack_app)
        @session = ::Rack::Test::Session.new(mock_session)
      end
...
```

I cannot find any code within `krane` that would activate rack, so it must be something in `shopify-core-datastores`.

**Comment by saunderst** [comment]
Thanks for the clarification.  I'll continue investigating on our side.

**Comment by saunderst** [comment]
This can happen if we don't manage dependencies explicitly.  Here was our solution, which may be helpful to illustrate the issue: https://github.com/Shopify/shopify-core-datastores/pull/799
